name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0, v2.1.3

jobs:
  build-and-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Match the project's Python version

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install build tools
        run: uv pip install --system build twine

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        run: uv twine upload --repository pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} # Store your PyPI API token as a GitHub secret
